version: "3"

services:
  database-diesel:
    container_name: database-diesel
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-diesel}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-diesel}
    ports:
      - "5432:5432"
    volumes:
      - db-diesel:/var/lib/postgresql/data:rw
  diesel-learn:
    container_name: diesel-learn
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-diesel}:${POSTGRES_PASSWORD:-password}@database-diesel/${POSTGRES_DB:-diesel}
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/diesel-learn
      - diesel-learn-target:/diesel/target
    depends_on:
      - database-diesel

volumes:
  # postgres data
  db-diesel:
  # rust data
  diesel-learn-target:
